language: node_js
node_js:
  - "11.6.0"

jobs:
  include:
  - stage: Build project
    script: yarn run build
  - stage: Produce Coverage
    script: jest --coverage --coverageReporters=text-lcov | coveralls
