image: Ubuntu1804
stack: node 12
cache: node_modules

branches:
  only:
    - master
  
install:
  - npm install
  
test_script:
  - npx jest --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
