environment:
  COVERALLS_REPO_TOKEN:
    secure: psgCntSJDXkDZgEvvzIu5+8SxXltLPT4ozgu6RvfsiiF6G2fAB6MQ+w4LvXs7skp

image: Ubuntu1804
stack: node 20

install:
  - npm install --global pnpm@latest
  - pnpm install

test_script:
  - pnpx jest --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
