environment:
  COVERALLS_REPO_TOKEN:
    secure: psgCntSJDXkDZgEvvzIu5+8SxXltLPT4ozgu6RvfsiiF6G2fAB6MQ+w4LvXs7skp
  nodejs_version: "20"

image: Ubuntu2004

install:
  - nvm use 20
  - npm install --global corepack@0.32.0
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm install

test_script:
  - pnpx jest --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
