environment:
  COVERALLS_REPO_TOKEN:
    secure: psgCntSJDXkDZgEvvzIu5+8SxXltLPT4ozgu6RvfsiiF6G2fAB6MQ+w4LvXs7skp

image: Ubuntu1804
stack: node 16

branches:
  only:
    - master

install:
  - npm ci

test_script:
  - npx jest --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls
